/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwIcs20Latest.types";
import * as _1 from "./CwIcs20Latest.client";
import * as _2 from "./Multicall.types";
import * as _3 from "./Multicall.client";
import * as _4 from "./OraiswapConverter.types";
import * as _5 from "./OraiswapConverter.client";
import * as _6 from "./OraiswapFactory.types";
import * as _7 from "./OraiswapFactory.client";
import * as _8 from "./OraiswapLimitOrder.types";
import * as _9 from "./OraiswapLimitOrder.client";
import * as _10 from "./OraiswapOracle.types";
import * as _11 from "./OraiswapOracle.client";
import * as _12 from "./OraiswapPair.types";
import * as _13 from "./OraiswapPair.client";
import * as _14 from "./OraiswapRewarder.types";
import * as _15 from "./OraiswapRewarder.client";
import * as _16 from "./OraiswapRouter.types";
import * as _17 from "./OraiswapRouter.client";
import * as _18 from "./OraiswapStaking.types";
import * as _19 from "./OraiswapStaking.client";
import * as _20 from "./OraiswapToken.types";
import * as _21 from "./OraiswapToken.client";
export namespace contracts {
  export const CwIcs20Latest = { ..._0,
    ..._1
  };
  export const Multicall = { ..._2,
    ..._3
  };
  export const OraiswapConverter = { ..._4,
    ..._5
  };
  export const OraiswapFactory = { ..._6,
    ..._7
  };
  export const OraiswapLimitOrder = { ..._8,
    ..._9
  };
  export const OraiswapOracle = { ..._10,
    ..._11
  };
  export const OraiswapPair = { ..._12,
    ..._13
  };
  export const OraiswapRewarder = { ..._14,
    ..._15
  };
  export const OraiswapRouter = { ..._16,
    ..._17
  };
  export const OraiswapStaking = { ..._18,
    ..._19
  };
  export const OraiswapToken = { ..._20,
    ..._21
  };
}
export * from "./types";