/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./OraiswapConverter.types";
import * as _1 from "./OraiswapConverter.client";
import * as _2 from "./OraiswapConverter.react-query";
import * as _3 from "./OraiswapFactory.types";
import * as _4 from "./OraiswapFactory.client";
import * as _5 from "./OraiswapFactory.react-query";
import * as _6 from "./OraiswapIbc.types";
import * as _7 from "./OraiswapIbc.client";
import * as _8 from "./OraiswapIbc.react-query";
import * as _9 from "./OraiswapOracle.types";
import * as _10 from "./OraiswapOracle.client";
import * as _11 from "./OraiswapOracle.react-query";
import * as _12 from "./OraiswapPair.types";
import * as _13 from "./OraiswapPair.client";
import * as _14 from "./OraiswapPair.react-query";
import * as _15 from "./OraiswapRewarder.types";
import * as _16 from "./OraiswapRewarder.client";
import * as _17 from "./OraiswapRewarder.react-query";
import * as _18 from "./OraiswapRouter.types";
import * as _19 from "./OraiswapRouter.client";
import * as _20 from "./OraiswapRouter.react-query";
import * as _21 from "./OraiswapStaking.types";
import * as _22 from "./OraiswapStaking.client";
import * as _23 from "./OraiswapStaking.react-query";
import * as _24 from "./OraiswapToken.types";
import * as _25 from "./OraiswapToken.client";
import * as _26 from "./OraiswapToken.react-query";
export namespace contracts {
  export const OraiswapConverter = { ..._0,
    ..._1,
    ..._2
  };
  export const OraiswapFactory = { ..._3,
    ..._4,
    ..._5
  };
  export const OraiswapIbc = { ..._6,
    ..._7,
    ..._8
  };
  export const OraiswapOracle = { ..._9,
    ..._10,
    ..._11
  };
  export const OraiswapPair = { ..._12,
    ..._13,
    ..._14
  };
  export const OraiswapRewarder = { ..._15,
    ..._16,
    ..._17
  };
  export const OraiswapRouter = { ..._18,
    ..._19,
    ..._20
  };
  export const OraiswapStaking = { ..._21,
    ..._22,
    ..._23
  };
  export const OraiswapToken = { ..._24,
    ..._25,
    ..._26
  };
}
export * from "./types";