import CollapseButton from '../Collapse';
import styles from './index.module.scss';

const FAQ = () => {
  return (
    <div className={styles.FAQ}>
      <div className={styles.title}>FAQ</div>

      <div className={styles.content}>
        {LIST_FAQ.map(({ question, answer }, key) => {
          return (
            <div key={key}>
              <CollapseButton label={question} content={answer} />
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default FAQ;

export const LIST_FAQ = [
  {
    question: 'What is ORAIX staking?',
    answer:
      "ORAIX Staking is a revenue-sharing program designed for ORAIX token holders. By locking their ORAIX tokens, participants earn a portion of OraiDEX's 10% weekly revenue."
  },
  {
    question: 'How does ORAIX Staking work?',
    answer:
      'ORAIX holders can lock their tokens into the staking program, and effectively participate in the long-term development of OraiDEX. In return, they receive a share of the 10% weekly revenue generated by OraiDEX (from liquidity fee, relayer fee, derivatives fee...)'
  },
  {
    question: 'How often are rewards distributed?',
    answer: "Rewards are distributed every week, corresponding to OraiDEX's revenue generated during that period."
  },
  {
    question: 'Is there a minimum requirement for staking?',
    answer: "No, you can deposit any amount of ORAIX available, this will also be your voting power for OraiDEX's DAO."
  },
  {
    question: 'Can I unstake my ORAIX tokens at any time?',
    answer:
      'While participants have the flexibility to unstake their tokens, there is a 30-day unbonding period before the tokens are released. This period allows for orderly management of liquidity and upholds fairness to other participants.'
  },
  {
    question: 'How are rewards calculated?',
    answer:
      'Rewards are calculated based on the proportion of ORAIX tokens staked by the participant relative to the total tokens staked in the program, as well as the amount of revenue distributed by OraiDEX (10% of total revenue).'
  },
  {
    question: 'What are the risks of staking ORAIX?',
    answer: (
      <div>
        Few risks to be considered:
        <br />
        <br />
        1. Technical risk: OraiDEX Staking Contract gets hacked and staked ORAIX is stolen.
        <br />
        <br />
        2. Liquidity risk: Staked ORAIX experiencing sudden price rallies or volatility, hindering trading due to locked
        tokens.
      </div>
    )
  }
];
