/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleMsg =
  | {
      update_config: {
        owner?: string | null;
        pair_code_id?: number | null;
        token_code_id?: number | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      create_pair: {
        /**
         * Asset infos
         */
        asset_infos: [AssetInfo, AssetInfo];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      register: {
        asset_infos: [AssetInfo, AssetInfo];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
/**
 * AssetInfo contract_addr is usually passed from the cw20 hook so we can trust the contract_addr is properly validated.
 */
export type AssetInfo =
  | {
      token: {
        contract_addr: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      native_token: {
        denom: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
