/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function computeSwapStep(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function getDeltaX(a: number, b: number, c: number, d: number, e: number): void;
export function getDeltaY(a: number, b: number, c: number, d: number, e: number): void;
export function getNextSqrtPriceFromInput(a: number, b: number, c: number, d: number, e: number): void;
export function getNextSqrtPriceFromOutput(a: number, b: number, c: number, d: number, e: number): void;
export function getNextSqrtPriceXUp(a: number, b: number, c: number, d: number, e: number): void;
export function getNextSqrtPriceYDown(a: number, b: number, c: number, d: number, e: number): void;
export function calculateAmountDelta(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function isEnoughAmountToChangePrice(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function calculateMaxLiquidityPerTick(a: number): number;
export function checkTicks(a: number, b: number, c: number, d: number): void;
export function checkTick(a: number, b: number, c: number): void;
export function calculateMinAmountOut(a: number, b: number): number;
export function tickToPositionJs(a: number, b: number, c: number): void;
export function positionToTick(a: number, b: number, c: number): number;
export function getGlobalMaxSqrtPrice(): number;
export function getGlobalMinSqrtPrice(): number;
export function getTickSearchRange(): number;
export function getMaxChunk(a: number): number;
export function getChunkSize(): number;
export function getMaxTickCross(): number;
export function getMaxTickmapQuerySize(): number;
export function getLiquidityTicksLimit(): number;
export function getMaxPoolKeysReturned(): number;
export function getMaxPoolPairsReturned(): number;
export function calculateFee(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number): void;
export function isTokenX(a: number, b: number, c: number, d: number, e: number): void;
export function checkTickToSqrtPriceRelationship(a: number, b: number, c: number, d: number): void;
export function alignTickToSpacing(a: number, b: number): number;
export function getTickAtSqrtPrice(a: number, b: number, c: number): void;
export function getLiquidityByX(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function getLiquidityByY(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function newFeeTier(a: number, b: number, c: number): void;
export function newPoolKey(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function simulateSwap(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function getFeeGrowthScale(): number;
export function getFeeGrowthDenominator(): number;
export function toFeeGrowth(a: number, b: number): number;
export function getFixedPointScale(): number;
export function getFixedPointDenominator(): number;
export function toFixedPoint(a: number, b: number): number;
export function getLiquidityScale(): number;
export function getLiquidityDenominator(): number;
export function toLiquidity(a: number, b: number): number;
export function getPercentageDenominator(): number;
export function toPercentage(a: number, b: number): number;
export function getPriceScale(): number;
export function getPriceDenominator(): number;
export function toPrice(a: number, b: number): number;
export function toSecondsPerLiquidity(a: number, b: number): number;
export function toSqrtPrice(a: number, b: number): number;
export function calculateSqrtPrice(a: number, b: number): void;
export function getMaxTick(a: number): number;
export function getMinTick(a: number): number;
export function getMaxSqrtPrice(a: number): number;
export function getMinSqrtPrice(a: number): number;
export function getTokenAmountScale(): number;
export function getTokenAmountDenominator(): number;
export function toTokenAmount(a: number, b: number): number;
export function getSecondsPerLiquidityDenominator(): number;
export function getSqrtPriceDenominator(): number;
export function getPercentageScale(): number;
export function getSecondsPerLiquidityScale(): number;
export function getSqrtPriceScale(): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
