/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IGravity, IGravityInterface } from "../../contracts/IGravity";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenContract",
        type: "address",
      },
      {
        internalType: "string",
        name: "_destination",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "sendToCosmos",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGravity__factory {
  static readonly abi = _abi;
  static createInterface(): IGravityInterface {
    return new utils.Interface(_abi) as IGravityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGravity {
    return new Contract(address, _abi, signerOrProvider) as IGravity;
  }
}
