/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0
 *
 * The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18)
 */
export type Decimal = string;

export interface InitMsg {
  admin?: HumanAddr | null;
  max_rate?: Decimal | null;
  min_rate?: Decimal | null;
  /**
   * name of the NFT contract, can use default
   */
  name?: string | null;
  version?: string | null;
  [k: string]: unknown;
}
